'use client';
import {useEffect,useState,useRef} from 'react';
import {NativeSelect} from '@/components/ui/native-select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Empty} from '@/components/ui/empty';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Clock3,Printer,Plus,Check,ClipboardList,LockKeyhole,Users,RefreshCw} from 'lucide-react';
type Intern={id:string;name:string;role:string};type Task={id:string;title:string;brief:string;steps:string;done:string;date:string;assignee:string|null;status:string;note:string};type Shift={id:string;intern:string;start:number;end:number|null;hours:number|null;approved:number;note:string;correction:string};type State={interns:Intern[];tasks:Task[];shifts:Shift[];teacher:boolean;configured:boolean};
const SESSION_KEY='steam-lab-teacher-session';
function sessionHeaders():Record<string,string>{const token=window.sessionStorage.getItem(SESSION_KEY);return token?{'x-lab-teacher-session':token}:{};}
async function readPortalResponse(r:Response):Promise<State & {error?:string;sessionToken?:string}>{
const body=await r.text();
let result:State & {error?:string;sessionToken?:string};
try{result=JSON.parse(body);}catch{
const interrupted=new Error(r.redirected||r.status===401||r.status===403?'Your site session needs to be refreshed. Reload this page, then reopen Teacher desk. Your saved interns are still there.':`The connection was interrupted (response ${r.status}). Your input is still here. Please try again.`) as Error & {retryable?:boolean};
interrupted.retryable=!r.redirected&&[200,429,500,502,503,504].includes(r.status);throw interrupted;
}
if(!r.ok){const error=new Error(result.error||`Could not save this change (response ${r.status}). Please retry.`) as Error & {retryable?:boolean};error.retryable=[429,500,502,503,504].includes(r.status);throw error;}
return result;
}
async function sendPortalAction(p:Record<string,unknown>){
const payload=p.action==='intern'?{...p,requestId:p.requestId||crypto.randomUUID()}:p;
for(let attempt=0;attempt<2;attempt++){
try{const r=await fetch('/api/portal',{method:'POST',cache:'no-store',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json',...sessionHeaders()},body:JSON.stringify(payload)});return await readPortalResponse(r);}
catch(error){const retryable=(error as Error & {retryable?:boolean}).retryable||error instanceof TypeError;if(payload.action!=='intern'||attempt>0||!retryable)throw error;await new Promise(resolve=>setTimeout(resolve,300));}
}
throw new Error('Could not save the intern. Please retry.');
}
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const initial:State={interns:[],tasks:[],shifts:[],teacher:false,configured:false};
const hours=(s:Shift)=>s.hours??((s.end??Date.now())-s.start)/3600000;
const stamp=(v:number)=>new Date(v).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
function Form({children,onSubmit,className=''}:{children:React.ReactNode;onSubmit:(p:Record<string,FormDataEntryValue>)=>Promise<boolean>;className?:string}){const [busy,setBusy]=useState(false);const requestId=useRef('');return <form className={className} onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;setBusy(true);try{if(!requestId.current)requestId.current=crypto.randomUUID();if(await onSubmit({...Object.fromEntries(new FormData(form)),requestId:requestId.current})){form.reset();requestId.current='';}}finally{setBusy(false);}}}><fieldset disabled={busy}>{children}</fieldset></form>}
export default function Page(){const [data,setData]=useState<State>(initial),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[view,setView]=useState('intern'),[tab,setTab]=useState('dispatch'),[person,setPerson]=useState(''),[date,setDate]=useState(day()),[now,setNow]=useState(Date.now()),[saving,setSaving]=useState(false);const [note,setNote]=useState('');
async function reload(){try{const r=await fetch('/api/portal',{cache:'no-store',headers:sessionHeaders()});const d=await readPortalResponse(r);setData(d);setLoaded(true);setError('');}catch(e){setError((e as Error).message);}}
useEffect(()=>{reload();const refresh=setInterval(reload,30000);const timer=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(refresh);clearInterval(timer);};},[]);
async function action(p:Record<string,unknown>){setSaving(true);setError('');setMessage('');try{const d=await sendPortalAction(p);if(p.action==='login'||p.action==='setup'){if(!d.sessionToken||!d.teacher)throw new Error('Teacher access could not be opened. Please retry.');window.sessionStorage.setItem(SESSION_KEY,d.sessionToken);const confirmation=await fetch('/api/portal',{cache:'no-store',headers:sessionHeaders()});const confirmed=await readPortalResponse(confirmation);if(!confirmation.ok||!confirmed.teacher){window.sessionStorage.removeItem(SESSION_KEY);throw new Error('The teacher session did not stay active. Please retry.');}setData(confirmed);setTab('dispatch');toast.success('Teacher desk is open');setMessage('Teacher desk is open');return true;}if(p.action==='logout'){window.sessionStorage.removeItem(SESSION_KEY);await reload();toast.success('Teacher desk locked');setMessage('Teacher desk locked');return true;}setData(d);toast.success('Saved');setMessage(p.action==='clockin'?'You’re clocked in.':p.action==='clockout'?'Shift saved for teacher review.':'Saved.');return true;}catch(e){setError((e as Error).message);return false;}finally{setSaving(false);}}
const intern=data.interns.find(i=>i.id===person),active=data.shifts.find(s=>s.intern===person&&s.end===null),mine=data.tasks.filter(t=>t.assignee===person&&t.date===date),open=data.tasks.filter(t=>!t.assignee&&t.date<=date&&t.status!=='Complete'),completed=mine.filter(t=>t.status==='Complete').length,approved=data.shifts.filter(s=>s.intern===person&&s.approved).reduce((a,s)=>a+hours(s),0);
const dateLabel=new Date(date+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'});
function Print(){return <button className="acid" disabled={!intern||!mine.length} onClick={()=>window.print()}><Printer size={17}/> Print my tasks</button>}
return <><Toaster theme="dark" position="bottom-right"/> <div className="app no-print"><header><a className="brand" href="/" aria-label="STEAM Lab home"><span className="mark">SL</span><span>STEAM LAB <span className="acid-text">//</span><small>INTERN DISPATCH</small></span></a><div className="top-actions"><button className={view==='intern'?'selected':''} onClick={()=>{setView('intern');setTab('dispatch');}}>Intern portal</button><button className={view==='teacher'?'selected':''} onClick={()=>{setView('teacher');setTab('dispatch');}}><LockKeyhole size={15}/> Teacher desk</button></div></header><main><div className="page-title"><div><p className="eyebrow">DAILY DISPATCH / SENIOR INTERNS</p><h1>{view==='intern'?'Make your mark.':'Run the lab.'}</h1><p className="subtitle">{view==='intern'?'Your time. Your tasks. Your contribution to the lab.':'Assign the work. Review the hours. Keep things moving.'}</p></div><div className="date-tile"><p className="eyebrow">LAB LOCAL TIME</p><strong>{new Date(now).toLocaleTimeString('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit'})}</strong><span>{new Date(now).toLocaleDateString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',year:'numeric'})}</span></div></div>
{error&&<div className="alert" role="alert">{error} <button onClick={reload}><RefreshCw size={15}/> Retry</button></div>}{message&&<div className="toast" role="status"><Check size={15}/>{message}</div>}{!loaded&&!error&&<Empty className="empty">Loading the lab…</Empty>}
{view==='intern'&&<><section className="controls"><label>Your name<NativeSelect value={person} onChange={e=>{setPerson(e.target.value);setNote('');}}><option value="">Select your name</option>{data.interns.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</NativeSelect></label><label>Dispatch date<input type="date" value={date} onChange={e=>{if(e.target.value)setDate(e.target.value);}}/></label><Print/></section>
{!intern?<section className="welcome"><div className="ticket-icon"><ClipboardList size={38}/></div><p className="eyebrow">READY WHEN YOU ARE</p><h2>Select your name.<br/>Find your next mission.</h2><p>{data.interns.length?'Clock in, check your dispatch, and pick up open lab work.':'Start at the Teacher desk to add your senior interns and first tasks.'}</p><div className="welcome-steps"><span>01 / CLOCK IN</span><span>02 / GET TO WORK</span><span>03 / LOG YOUR DAY</span></div></section>:<><div className="stats"><div className="stat"><span>TODAY’S DISPATCH</span><strong>{mine.length.toString().padStart(2,'0')}<small> tasks</small></strong></div><div className="stat"><span>COMPLETED</span><strong>{completed.toString().padStart(2,'0')}<small> / {mine.length}</small></strong></div><div className="stat"><span>APPROVED TIME / ALL DATES</span><strong>{approved.toFixed(1)}<small> hrs</small></strong></div></div><div className="workspace"><section><div className="section-head"><div><p className="eyebrow">{intern.role}</p><h2>{intern.name}’s dispatch</h2></div><span className="date-label">{dateLabel}</span></div><Tabs value={tab} onValueChange={setTab}><TabsList className="tabs" variant="line"><TabsTrigger value="dispatch">My tasks <b>{mine.length}</b></TabsTrigger><TabsTrigger value="board">Open lab work <b>{open.length}</b></TabsTrigger><TabsTrigger value="hours">My time</TabsTrigger></TabsList></Tabs>
{tab==='dispatch'&&(mine.length?mine.map((t,i)=><TaskCard key={t.id} task={t} number={i+1} busy={saving} onSave={(status,n)=>action({action:'progress',id:t.id,intern:person,status,note:n})}/>):<Empty className="empty"><ClipboardList size={30}/><h3>No tasks assigned for this date.</h3><p>Pick a task from Open lab work or check in with Imani.</p><button onClick={()=>setTab('board')}>View open lab work</button></Empty>)}
{tab==='board'&&<><p className="helper">Claim a task to add it to your dispatch. Older open tasks stay available.</p>{open.length?open.map((t,i)=><article className="task" key={t.id}><div className="task-top"><span className="eyebrow">LAB WORK / {String(i+1).padStart(2,'0')}</span><span className="badge">Available</span></div><h3>{t.title}</h3><p>{t.brief}</p><p className="muted">Scheduled {t.date}</p><div className="definition"><span>DEFINITION OF DONE</span><p>{t.done||'Complete the checklist and leave an end-of-task note.'}</p></div><button className="acid" disabled={saving} onClick={async()=>{if(await action({action:'claim',id:t.id,intern:person})){setDate(t.date);setTab('dispatch');}}}><Plus size={16}/> Claim task</button></article>):<Empty className="empty"><Check size={30}/><h3>The open board is clear.</h3><p>New lab tasks will appear here when Imani adds them.</p></Empty>}</>}
{tab==='hours'&&<div className="time-list">{data.shifts.filter(s=>s.intern===person).map(s=><div className="time-item" key={s.id}><div><strong>{stamp(s.start)}</strong><p>{s.end?`Clocked out ${stamp(s.end)}`:'Currently clocked in'}</p>{s.note&&<p>{s.note}</p>}{s.correction&&<p>Teacher note: {s.correction}</p>}</div><div><strong>{hours(s).toFixed(2)} hrs</strong><span className={'badge '+(s.approved?'complete':'')}>{s.approved?'Approved':s.end?'Awaiting review':'Active shift'}</span></div></div>)}{!data.shifts.some(s=>s.intern===person)&&<Empty className="empty">Your first shift will appear here after you clock in.</Empty>}</div>}
</section><aside><div className={'clock-card '+(active?'clocked':'')}><p className="eyebrow">TIME IN THE LAB</p><Clock3 size={24}/><h3>{active?'You’re on the clock.':'Ready to clock in?'}</h3><div className="timer">{active?`${Math.floor((now-active.start)/3600000).toString().padStart(2,'0')}:${Math.floor((now-active.start)/60000%60).toString().padStart(2,'0')}:${Math.floor((now-active.start)/1000%60).toString().padStart(2,'0')}`:'00:00:00'}</div><p>{active?`Started ${stamp(active.start)}`:'Clock in when you arrive. Clock out before you leave.'}</p>{active&&<label>Shift notes<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="What did you work on? Anything to pass along?" rows={3}/></label>}<button className={active?'':'acid'} disabled={saving} onClick={async()=>{if(await action({action:active?'clockout':'clockin',intern:person,note}))setNote('');}}>{active?'Clock out & save shift':'Clock in'}</button><span className="clock-foot">Hours are confirmed by your teacher.</span></div><div className="print-card"><Printer size={25}/><h3>Take your dispatch.</h3><p>Print your tasks and checklist on an 80 mm receipt.</p><Print/><p className="micro">Choose the receipt printer in the print dialog. Use 80 mm paper, 100% scale, and turn off headers and footers.</p></div></aside></div></>}
</>}
{view==='teacher'&&(!data.teacher?<section className="login"><LockKeyhole size={26}/><p className="eyebrow">TEACHER ACCESS</p><h2>{data.configured?'Welcome back.':'Set up your desk.'}</h2><p>{data.configured?'Enter your PIN to manage interns, tasks, and time.':'Choose a 6–12 digit teacher PIN, then add your interns. Use the teacher setup key from Vercel to protect first-time setup.'}</p><Form onSubmit={p=>action({action:data.configured?'login':'setup',...p})}>{!data.configured&&<label>Teacher setup key<input name="setupKey" type="password" required autoComplete="off"/></label>}<label>Teacher PIN<input type="password" inputMode="numeric" name="pin" required pattern="[0-9]{6,12}" minLength={6} maxLength={12} autoComplete={data.configured?'current-password':'new-password'}/></label><button className="acid">{data.configured?'Open teacher desk':'Save PIN & open desk'}</button></Form></section>:<><div className="teacher-head"><h2>Teacher desk</h2><button onClick={()=>action({action:'logout'})}><LockKeyhole size={15}/> Lock desk</button></div><Tabs value={tab} onValueChange={setTab}><TabsList className="tabs" variant="line"><TabsTrigger value="dispatch">Tasks</TabsTrigger><TabsTrigger value="roster">Intern roster</TabsTrigger><TabsTrigger value="review">Time review <b>{data.shifts.filter(s=>s.end&&!s.approved).length}</b></TabsTrigger></TabsList></Tabs>
{tab==='dispatch'||tab==='board'||tab==='hours'?<div className="teacher-grid"><section className="panel"><div className="panel-head"><Plus size={19}/><h3>Create lab work</h3></div><Form onSubmit={p=>action({action:'task',...p})}><label>Task title<input name="title" required maxLength={150} placeholder="e.g. Organize the tool bin"/></label><div className="form-two"><label>Scheduled date<input name="date" type="date" defaultValue={day()} required/></label><label>Assign to<NativeSelect name="intern"><option value="">Open for interns to claim</option>{data.interns.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</NativeSelect></label></div><label>Task brief<textarea name="brief" rows={3} placeholder="What needs to happen and why?"/></label><label>Checklist — one step per line<textarea name="steps" rows={4} placeholder={'Sort tools by type\nLabel each section\nReport any damaged tools'}/></label><label>Definition of done<textarea name="done" rows={2} placeholder="What should the finished work look like?"/></label><button className="acid"><Plus size={16}/> Publish task</button></Form></section><section><div className="section-head"><h2>Lab task list</h2><span className="badge">{data.tasks.length} tasks</span></div>{!data.tasks.length?<Empty className="empty"><h3>Start with your lab priorities.</h3><p>Create your first task or add tool-bin and closet organization tasks.</p><button disabled={saving} onClick={()=>action({action:'starter'})}>Add two starter tasks</button></Empty>:data.tasks.map(t=><article className="task compact" key={t.id}><div className="task-top"><span className="eyebrow">{t.date}</span><span className={'badge '+(t.status==='Complete'?'complete':'')}>{t.status}</span></div><h3>{t.title}</h3><p>{t.brief}</p><label>Assigned intern<NativeSelect value={t.assignee||''} disabled={saving} onChange={e=>action({action:'assign',id:t.id,intern:e.target.value})}><option value="">Open for interns to claim</option>{data.interns.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</NativeSelect></label>{t.note&&<p className="definition">Intern note: {t.note}</p>}<AlertDialog><AlertDialogTrigger asChild><button className="delete" disabled={saving}>Delete task</button></AlertDialogTrigger><AlertDialogContent className="confirm-dialog"><AlertDialogTitle>Delete this task?</AlertDialogTitle><AlertDialogDescription>“{t.title}” will be removed from the lab list and intern dispatch.</AlertDialogDescription><div className="dialog-actions"><AlertDialogCancel>Keep task</AlertDialogCancel><AlertDialogAction onClick={()=>action({action:'deleteTask',id:t.id})}>Delete task</AlertDialogAction></div></AlertDialogContent></AlertDialog></article>)}</section></div>:null}
{tab==='roster'&&<div className="teacher-grid"><section className="panel"><div className="panel-head"><Users size={19}/><h3>Add an intern</h3></div><Form onSubmit={p=>action({action:'intern',...p})}><label>Name<input name="name" required maxLength={80} placeholder="Intern’s name"/></label><label>Lab role<input name="role" maxLength={100} placeholder="Lab intern"/></label><button className="acid"><Plus size={16}/> Add intern</button></Form></section><section><h2>Your senior interns</h2>{data.interns.map(i=><div className="roster-row" key={i.id}><span className="avatar">{i.name.slice(0,1).toUpperCase()}</span><div><h3>{i.name}</h3><p>{i.role}</p></div><strong>{data.shifts.filter(s=>s.intern===i.id&&s.approved).reduce((a,s)=>a+hours(s),0).toFixed(1)}<small> approved hrs</small></strong></div>)}{!data.interns.length&&<Empty className="empty">Add your seniors here. Their names will appear in the intern portal.</Empty>}</section></div>}
{tab==='review'&&<div className="teacher-grid"><section className="panel"><div className="panel-head"><Clock3 size={19}/><h3>Add a missed shift</h3></div><Form onSubmit={p=>action({action:'manual',intern:p.intern,start:new Date(String(p.start)).getTime(),end:new Date(String(p.end)).getTime(),note:p.note})}><label>Intern<NativeSelect name="intern" required><option value="">Select an intern</option>{data.interns.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</NativeSelect></label><label>Start (this device’s local time)<input name="start" type="datetime-local" required/></label><label>End (this device’s local time)<input name="end" type="datetime-local" required/></label><label>Shift notes<textarea name="note" rows={3}/></label><button className="acid">Add shift for review</button></Form></section><section><h2>Hours & activity</h2><p className="helper">Recorded time stays visible. Enter confirmed hours and a correction note before approving.</p>{data.shifts.map(s=><article className="task" key={s.id}><div className="task-top"><strong>{data.interns.find(i=>i.id===s.intern)?.name}</strong><span className={'badge '+(s.approved?'complete':'')}>{s.approved?'Approved':s.end?'Needs review':'Clocked in'}</span></div><p>{stamp(s.start)}{s.end?' — '+stamp(s.end):' — Active shift'}</p><p>Recorded duration: {(((s.end??now)-s.start)/3600000).toFixed(2)} hours</p>{s.note&&<div className="definition">{s.note}</div>}{s.end&&<Form key={`${s.id}-${s.hours}-${s.approved}`} onSubmit={p=>action({action:'review',id:s.id,hours:p.hours,correction:p.correction,approved:p.approved==='on'})}><label>Confirmed hours<input name="hours" type="number" min="0" max="24" step="0.01" required defaultValue={hours(s).toFixed(2)}/></label><label>Teacher / correction note<input name="correction" defaultValue={s.correction} placeholder="Reason for any adjustment"/></label><label className="check-label"><Checkbox name="approved" defaultChecked={!!s.approved}/> Approve these hours</label><button className="acid">Save review</button></Form>}</article>)}{!data.shifts.length&&<Empty className="empty">Clock-ins and manual entries will appear here.</Empty>}</section></div>}
</>)}<footer><span>STEAM LAB // INTERN DISPATCH</span><span>BUILD. ORGANIZE. MAKE THINGS HAPPEN.</span></footer></main></div>
<section className="receipt"><div className="receipt-center"><h2>STEAM LAB</h2><strong>INTERN DAILY DISPATCH</strong><p>{date}</p></div><hr/><h2>{intern?.name}</h2><p>{intern?.role}</p><hr/>{mine.map((t,i)=><article key={t.id}><p>TASK {i+1} / {t.status.toUpperCase()}</p><h3>{t.title}</h3><p>{t.brief}</p>{t.steps.split('\n').filter(Boolean).map((s,n)=><p key={n}>[ ] {s}</p>)}{t.done&&<p><strong>DONE WHEN:</strong> {t.done}</p>}<hr/></article>)}<p>END-OF-DAY NOTES:</p><p>________________________________</p><p>________________________________</p><p className="receipt-center">Clock out before you leave.<br/>STEAM LAB // DAILY DISPATCH</p></section></>;
}
function TaskCard({task:t,number,busy,onSave}:{task:Task;number:number;busy:boolean;onSave:(status:string,note:string)=>Promise<boolean>}){const [note,setNote]=useState(t.note),[status,setStatus]=useState(t.status);useEffect(()=>{setStatus(t.status);setNote(t.note);},[t.status,t.note]);return <article className={'task '+(t.status==='Complete'?'finished':'')}><div className="task-top"><span className="eyebrow">MISSION / {String(number).padStart(2,'0')}</span><span className={'badge '+(t.status==='Complete'?'complete':'')}>{t.status}</span></div><h3>{t.title}</h3><p>{t.brief}</p><div className="steps">{t.steps.split('\n').filter(Boolean).map((step,i)=><div key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{step}</p></div>)}</div><div className="definition"><span>DEFINITION OF DONE</span><p>{t.done||'Finish the checklist and add a task note.'}</p></div><div className="task-update"><label>Mission status<NativeSelect value={status} onChange={e=>setStatus(e.target.value)}>{['Not started','In progress','Needs help','Complete'].map(s=><option key={s}>{s}</option>)}</NativeSelect></label><label>Task notes<textarea rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder="What’s done? What needs attention?"/></label><button disabled={busy} onClick={()=>onSave(status,note)}><Check size={16}/> Save progress</button></div></article>}
