import {database} from '@/lib/store';
export const runtime='nodejs';
export const dynamic='force-dynamic';
const encoder=new TextEncoder();
async function digest(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
async function pinHash(pin:string,salt:string){const key=await crypto.subtle.importKey('raw',encoder.encode(pin),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:encoder.encode(salt),iterations:100000,hash:'SHA-256'},key,256);return Array.from(new Uint8Array(bits)).map(x=>x.toString(16).padStart(2,'0')).join('');}
function teacherToken(r:Request){return r.headers.get('x-lab-teacher-session')||r.headers.get('cookie')?.match(/(?:^|; )lab_teacher=([^;]+)/)?.[1];}
async function isTeacher(r:Request){const db=database();const token=teacherToken(r);if(!token)return false;const entry=await db.prepare('SELECT value FROM settings WHERE key=?').bind('session:'+await digest(token)).first<{value:string}>();return !!entry&&Number(entry.value)>Date.now();}
async function state(r:Request){const db=database();const teacher=await isTeacher(r);const configured=!!await db.prepare('SELECT key FROM settings WHERE key=?').bind('pin').first();const [a,b,c]=await Promise.all([db.prepare('SELECT * FROM interns ORDER BY name').all(),db.prepare('SELECT * FROM tasks ORDER BY date DESC,title').all(),db.prepare('SELECT * FROM shifts ORDER BY start DESC').all()]);return {interns:a.results,tasks:b.results,shifts:c.results,teacher,configured};}
export async function GET(r:Request){try{return Response.json(await state(r),{headers:{'Cache-Control':'no-store'}});}catch(e){console.error(e);return Response.json({error:'Could not load the portal. Check the Turso connection and run the database SQL before retrying.'},{status:503});}}
export async function POST(r:Request){try{if(r.headers.get('origin')&&r.headers.get('origin')!==new URL(r.url).origin)return Response.json({error:'Please use the portal to save changes.'},{status:403});const p=await r.json() as Record<string,any>;const db=database();const fail=(s:string)=>Response.json({error:s},{status:400});const str=(v:unknown,max=3000)=>typeof v==='string'?v.trim().slice(0,max):'';const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
if(p.action==='login'||p.action==='setup'){
const pin=str(p.pin,100);let stored=await db.prepare('SELECT value FROM settings WHERE key=?').bind('pin').first<{value:string}>();
if(p.action==='setup'){if(stored)return fail('Teacher access is already configured.');if(!process.env.TEACHER_SETUP_KEY||process.env.TEACHER_SETUP_KEY.length<20||await digest(str(p.setupKey,200))!==await digest(process.env.TEACHER_SETUP_KEY))return Response.json({error:'Enter the teacher setup key from your Vercel environment variables.'},{status:403});if(!/^\d{6,12}$/.test(pin))return fail('Use a PIN with 6–12 digits.');const salt=crypto.randomUUID();const value=salt+':'+await pinHash(pin,salt);await db.prepare('INSERT INTO settings(key,value) VALUES(?,?)').bind('pin',value).run();stored={value};}
if(!stored)return fail('Set up teacher access first.');const [salt,hash]=stored.value.split(':');if(await pinHash(pin,salt)!==hash)return Response.json({error:'That PIN did not match.'},{status:403});const token=crypto.randomUUID()+crypto.randomUUID();await db.prepare('INSERT INTO settings(key,value) VALUES(?,?)').bind('session:'+await digest(token),String(Date.now()+8*3600000)).run();const sessionHeaders=new Headers(r.headers);sessionHeaders.set('x-lab-teacher-session',token);const sessionState=await state(new Request(r.url,{headers:sessionHeaders}));return Response.json({...sessionState,sessionToken:token},{headers:{'Cache-Control':'no-store','Set-Cookie':`lab_teacher=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800`}});
}
if(p.action==='logout'){const token=teacherToken(r);if(token)await db.prepare('DELETE FROM settings WHERE key=?').bind('session:'+await digest(token)).run();return Response.json({ok:true},{headers:{'Cache-Control':'no-store','Set-Cookie':'lab_teacher=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0'}});}
const teacher=await isTeacher(r);
const teacherActions=['intern','task','assign','deleteTask','review','manual','starter'];if(teacherActions.includes(p.action)&&!teacher)return Response.json({error:'Open teacher access to make this change.'},{status:403});
const internId=str(p.intern,100);const intern=internId?await db.prepare('SELECT id FROM interns WHERE id=?').bind(internId).first():null;
if(p.action==='intern'){
const name=str(p.name,80),role=str(p.role,100)||'Lab intern';if(!name)return fail('Enter an intern name.');
const requestId=str(p.requestId,100);if(requestId&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(requestId))return fail('Please retry adding the intern.');
const id=requestId||crypto.randomUUID();
await db.prepare('INSERT INTO interns(id,name,role) VALUES(?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,name,role).run();
const saved=await db.prepare('SELECT name,role FROM interns WHERE id=?').bind(id).first<{name:string;role:string}>();
if(!saved||saved.name!==name||saved.role!==role)return Response.json({error:'This save request is already used. Please submit again.'},{status:409});
}
else if(p.action==='task'){if(!str(p.title,150)||!/^\d{4}-\d{2}-\d{2}$/.test(p.date))return fail('Enter a task title and date.');if(internId&&!intern)return fail('Choose an existing intern.');await db.prepare('INSERT INTO tasks(id,title,brief,steps,done,date,assignee,status,note) VALUES(?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),str(p.title,150),str(p.brief),str(p.steps),str(p.done),p.date,internId||null,'Not started','').run();}
else if(p.action==='assign'){if(internId&&!intern)return fail('Choose an existing intern.');await db.prepare('UPDATE tasks SET assignee=? WHERE id=?').bind(internId||null,str(p.id,100)).run();}
else if(p.action==='deleteTask'){await db.prepare('DELETE FROM tasks WHERE id=?').bind(str(p.id,100)).run();}
else if(p.action==='claim'){if(!intern)return fail('Select your name first.');const result=await db.prepare("UPDATE tasks SET assignee=? WHERE id=? AND assignee IS NULL AND status!='Complete'").bind(internId,str(p.id,100)).run();if(!result.meta.changes)return fail('Someone has already claimed this task. Refresh the board.');}
else if(p.action==='progress'){if(!intern||!['Not started','In progress','Needs help','Complete'].includes(p.status))return fail('Choose your name and a valid status.');const result=await db.prepare('UPDATE tasks SET status=?,note=? WHERE id=? AND assignee=?').bind(p.status,str(p.note),str(p.id,100),internId).run();if(!result.meta.changes)return fail('This task is not assigned to you.');}
else if(p.action==='clockin'){if(!intern)return fail('Select your name first.');const result=await db.prepare('INSERT INTO shifts(id,intern,start,end,hours,approved,note,correction) SELECT ?,?,?,NULL,NULL,0,?,? WHERE NOT EXISTS(SELECT 1 FROM shifts WHERE intern=? AND end IS NULL)').bind(crypto.randomUUID(),internId,Date.now(),'','',internId).run();if(!result.meta.changes)return fail('You are already clocked in.');}
else if(p.action==='clockout'){if(!intern)return fail('Select your name first.');const result=await db.prepare('UPDATE shifts SET end=?,note=? WHERE intern=? AND end IS NULL').bind(Date.now(),str(p.note),internId).run();if(!result.meta.changes)return fail('No active shift was found.');}
else if(p.action==='review'){const hours=Number(p.hours);if(!Number.isFinite(hours)||hours<0||hours>24)return fail('Hours must be between 0 and 24.');const s=await db.prepare('SELECT * FROM shifts WHERE id=?').bind(str(p.id,100)).first();if(!s||s.end===null)return fail('Clock out before reviewing this shift.');await db.prepare('UPDATE shifts SET hours=?,approved=?,correction=? WHERE id=?').bind(hours,p.approved?1:0,str(p.correction),str(p.id,100)).run();}
else if(p.action==='manual'){if(!intern)return fail('Choose an intern.');const start=Number(p.start),end=Number(p.end);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start||end-start>24*3600000)return fail('Enter a valid shift of up to 24 hours.');await db.prepare('INSERT INTO shifts(id,intern,start,end,hours,approved,note,correction) VALUES(?,?,?,?,NULL,0,?,?)').bind(crypto.randomUUID(),internId,start,end,str(p.note),'Manual entry').run();}
else if(p.action==='starter'){const statements=[['Organize the tool bin','Make the tools easy to find and return.','Sort tools by type\nCheck for missing or damaged tools\nLabel each section\nReturn everything to its section','A labeled bin with all tools accounted for.'],['Organize the lab closet','Reset the closet so supplies are easy to access.','Sort materials by type\nKeep walkways clear\nLabel shelves and bins\nMake a list of supplies running low','Organized shelves and a supply list for Imani.']].map(t=>db.prepare('INSERT INTO tasks(id,title,brief,steps,done,date,assignee,status,note) VALUES(?,?,?,?,?,?,NULL,?,?)').bind(crypto.randomUUID(),...t,today,'Not started',''));await db.batch(statements);}
else return fail('Unknown action.');return Response.json(await state(r),{headers:{'Cache-Control':'no-store'}});
}catch(e){console.error(e);return Response.json({error:'Could not save this change. Your input is still here; please retry.'},{status:503});}}
